batch_size: 200
valid_split: 0.2
dir:
    data: /data/01.datasets/100peopleRegistBank
    test: /data/01.datasets/100peopleBank
    faceback: /data/01.datasets/facebank
    output: ./output
epochs: 1000
shape: [480, 640]
classes: 100
